name: "zibun-releaser"
description: "zibun-releaser"
inputs:
  release-version:
    description: "new release version"
    required: true
    default: "v0.0.0"
  filepath:
    description: "markdown file path"
    required: true
    default: ""
  apikey:
    description: "gemini api key"
    required: true
    default: ""
  github-pat:
    description: "github paesonal access token"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - run: ./${{ github.action_path }}/build/main
      shell: bash
      env:
        ENV: "CI"
        FILEPATH: ${{ inputs.filepath }}
        APIKEY: ${{ inputs.apikey}}

    - run: git tag -a -m "$(cat /tmp/releasenote.md)" ${{ inputs.release-version }}
      shell: bash

    - run: git push --follow-tags
      shell: bash
    
    - use: GitHubRelease@0 
      with:
        gitHubConnection: ${{ inputs.github-pat}}
        tag: ${{ inputs.release-version }}
        title: "じぶんリリースノート $(date "+%Y/%m")"
        releaseNotesSource: file
        releaseNotesFile: "/tmp/releasenote.md"
