name: "zibun-releaser"
description: "zibun-releaser"
inputs:
  release-version:
    description: "new release version"
    required: true
    default: "v0.0.0"
  filepath:
    description: "markdown file path"
    required: true
    default: ""
  apikey:
    description: "gemini api key"
    required: true
    default: ""
  github-token:
    description: "github paesonal access token"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      shell: bash

    - run: ${{ github.action_path }}/build/main
      shell: bash
      env:
        ENV: "CI"
        FILEPATH: ${{ inputs.filepath }}
        APIKEY: ${{ inputs.apikey}}

    - run: git tag -a -m "$(cat /tmp/releasenote.md)" ${{ inputs.release-version }}
      shell: bash

    - run: git push --follow-tags
      shell: bash

    - run: |
        gh release create ${{ inputs.release-version }} \
          --title "じぶんリリースノート $(date "+%Y/%m")" \
          --notes-file /tmp/releasenote.md
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
