name: Backend Test

on:
  push:
  pull_request:

jobs:
  golang-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: testing
        run: |
          cd backend
          go test ./... -coverprofile=coverage.out

      - name: create report
        uses: k1LoW/octocov-action@v0
  
  golang-cilint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=5m --config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
